# -*- coding: utf-8 -*-
"""Analise_dados_textuais_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-1FYVIWjz5P3Qqj63Wyoi2KbR7HthOwR
"""

print("Curso: Ciência de Dados")
print("Disciplina: Analise de Dados Textuais")
print("Alauno: Ernesto Gurgel Valente Neto")

"""### **Inicio do Codigos do Trabalhos de Ciencia de Dados - Analise de Dados Textuais**"""

print('Importação de Pacotes')
import nltk

nltk.download('gutenberg')

nltk.download('punkt')

nltk.corpus.gutenberg.fileids()

"""**Total de Palavras do Livro Moby Dick**

"""

md = nltk.corpus.gutenberg.words('melville-moby_dick.txt')

"""**Quantidade total de palavras**"""

len(md)

"""**As palavras (Tokens) não repetidas**"""

#md_dist = set(mb)

#len(md_dist)

#porc = len(md_dist)/len(md)

#porc*100

#sent_md = nltk.corpus.gutenberg.sents("melville-moby_dick.txt")

#sent_md

#len(sent_mb)

"""**Analise texto Acile No pais das Maravilhas**"""

alice = nltk.corpus.gutenberg.words('carroll-alice.txt')
len(alice)

sent_alice = nltk.corpus.gutenberg.sents("carroll-alice.txt")
sent_alice
len(sent_alice)

"""**Operacao em documentos (Varrendo vetor de documentos)**"""

gutenberg_list = nltk.corpus.gutenberg.fileids()
gutenberg_documents = nltk.corpus.gutenberg.words(gutenberg_list)

for documents in nltk.corpus.gutenberg.fileids():
    words_total = len(nltk.corpus.gutenberg.words(documents))
    print(words_total, documents)

documents_len = [(len(nltk.corpus.gutenberg.words(documents)), documents)
  for documents in nltk.corpus.gutenberg.fileids()]

max(documents_len)

min(documents_len)

"""# **Analise de Quantidade de Palavras do Livro**"""

for documents in nltk.corpus.gutenberg.fileids():
  words_total = len(nltk.corpus.gutenberg.words(documents))
  sents_total = len(nltk.corpus.gutenberg.sents(documents))

mean = words_total/sents_total
mean

alice = nltk.corpus.gutenberg.words("carroll-alice.txt")

alice

"""### **Palavra mais frequente**"""

aliceFreq = nltk.FreqDist(alice)

aliceFreq

aliceFreq["Rabbit"]

aliceFreq.most_common(1)

aliceFreq.most_common(15)

"""### **Analise Moby Dick mais frequente**"""

mb_words = nltk.corpus.gutenberg.words("melville-moby_dick.txt")

mb_wordsFreq= nltk.FreqDist(mb_words)

mb_wordsFre

mb_wordsFre.most_common(1)

mb_wordsFre.most_common(15)

"""mob_100 = mb_wordsFre.most_common(100)

### **Colocando as palavras da primeira posicao em uma lista**
"""

mob_100 = [word[0] for word in mob_100]

"""#esse for é como se tivesse assim:
#    alice_100 = []
#   for word in aliceFre_100:
#        alice_100.append(word[0])
"""

mob_100

alice_100 = mb_wordsFre.most_common(100)

alice_100

alice_100 = [word[0] for word in alice_100]

alice_100

diferenca_Nao_Tem_Um_no_Outro = list(set(alice_100) - set(mob_100))

diferenca_Nao_Tem_Um_no_Outro