# -*- coding: utf-8 -*-
"""Analise_dados_textuais_12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MZjtez-0w9s-IL2Bm6Cp1Y7N9IAkwcjA

# **Parte 1 Revisão**
"""

import nltk

nltk.download('gutenberg')

nltk.corpus.gutenberg.fileids()

alice = nltk.corpus.gutenberg.words('carroll-alice.txt')

alice_freq = nltk.FreqDist(alice)

alice_100 = alice_freq.most_common(100)

alice_common = []

for word in alice_100:
  #word[0], word[1]
  alice_common.append(word[0])

alice_common

common = set(word.lower() for word in alice_common if word.isalpha())

nltk.download('stopwords')

stopwords = nltk.corpus.stopwords.words('english')

stopwords = nltk.corpus.stopwords.words()

conjunto_final = list(set(common) - set(stopwords))

"""**# importando arquivos da maquina**"""

from google.colab import files

#uploaded1 = files.upload()

uploaded = files.upload()