# -*- coding: utf-8 -*-
"""Analise_dados_textuais_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U8QpSse19UIpQn0qDDbLmZ9wCoPJYl_s
"""

import nltk

nltk.download('gutenberg')

alice = nltk.corpus.gutenberg.words('carroll-alice.txt')

alice

alice_freq = nltk.FreqDist(alice)

alice_freq

alice_100 = alice_freq.most_common(100)

len(alice_100)

alice_100

"""Normalizar os dados"""

alice_common = []

for word in alice_100:
  alice_common.append(word[0])

# alice_common = [word[0] for word in alice_100]

alice_common

common = set(word.lower() for word in alice_common if word.isalpha())

common

len(common)

"""Tratando as StopWords"""

nltk.download('stopwords')

stopwords = nltk.corpus.stopwords.words('english')

stopwords

len(stopwords)

conjunto_final = list(set(common) - set(stopwords))

conjunto_final

len(conjunto_final)

"""Incluir um único arquivo"""

from google.colab import files

#uploaded = files.upload()

#uploaded = files.upload()

from google.colab import drive

drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

"""#Leitura de Arquivos"""

#text = open("exemplo.txt").read()

#text

"""Tegeando"""

nltk.download('punkt')

nltk.download('averaged_perceptron_tagger')

#text_tag = nltk.pos_tag(nltk.word_tokenize(text))

#text_tag