# -*- coding: utf-8 -*-
"""Aula_2_Regex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PzD-6MBVAIyYYSGu-IyI_ajeflMBSwWR

**### Aula sobre Regex**
"""

import nltk

import re

nltk.download('gutenberg')

alice = nltk.corpus.gutenberg.words('carroll-alice.txt')

alice

"""**# Encontrando a string new no corpus**

> Bloco com avanço


"""

#procura dados casados
re.fullmatch()
#buscar determinado padrao ou contexto
re.search()

for word in alice:
  if re.search("^...$",word):
    lista_word_re.append(word)

lista_word_re = []